### ISSUE TITLE
Capital D in Dappfile

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#200]
should we rename `dappfile` to `Dappfile`?

**Comment by nmushegian** [comment]
I've always thought of `dapple` as being explicitly lowercase, like `git` is rarely written out as "Git".

But it seems that the natural trend is towards "Dapple". I don't care that much, I just have a random aesthetic preference.

**Comment by dbrock** [comment]
The reason I brought this up is simply that the names of these "`Whateverfile`s" are usually capitalized (`Makefile`, `Rakefile`, `Gemfile`, `Procfile`, `Dockerfile`, `Vagrantfile`, etc., etc.) &mdash; despite the fact that e.g. `makefile` is also recognized, at least by GNU Make &mdash; so I guess I've just come to expect it.

As for the name of the project as written in prose, I guess you could go either way but I agree that the natural tendency will be towards "Dapple" since it just makes the most sense. I would actually go so far as to say that "Git" is always capitalized in prose (for example, in all the official documentation).

**Comment by nmushegian** [comment]
Alright I'm convinced

**Comment by mhhf** [comment]
The best strategy here would be to support both and throw a warning if dapple with a lower case d is used. However, this should take a little work since the filename is distributed across the project :(

**Comment by ryepdx** [comment]
I believe this was handled in b2381f8d8be264a904e849178769969cd9130d14
