### ISSUE TITLE
Subpackage tests should be excluded from `dapple test` by default

### ISSUE THREAD

**Issue by ryepdx** [nexusdev/dapple#258]
The `--subpackages` flag should bring subpackage tests back in.

**Comment by mhhf** [comment]
cannot confirm this either.
tested this on a toy project with dappsys dependency. dappsys' tests are run along with `dapple test --subpackages`. Tested on the v0.8 branch, bud should also work on v0.7.2 since i never touched this feature. 
Can you test this again and provide your dapple version and the project you've tested this on in case this don't work for you?

**Comment by mhhf** [comment]
works on v0.8. Please reopen if you still have problems with this
