### ISSUE TITLE
default gas too low?

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#351]
I'm getting OOG errors for tests that used to pass:

https://github.com/nexusdev/ds-base

**Comment by mhhf** [comment]
hmm strange, during testing, max gas is passed.
could reproduce it. will look at this in depth

**Comment by ethernomad** [comment]
Is it the same as this issue: https://github.com/nexusdev/dapple-test/issues/3 ?

**Comment by mhhf** [comment]
Don't think so, this was solved in ethereumjs-vm 2.0.1 and is included in the latest dapple version so at least this shouldn't be the same error, but i have to dig a little bit around to find the real cause of this

**Comment by mhhf** [comment]
@nmushegian Its not a dapple issue but a change in solidity requires to explicitly mark functions which are payable, otherwise a throw is produced. Also OOG is the only error the evm can produce, so all throws will be OOG...
you can solve this by adding the `payable` modifier to the fallback function here: https://github.com/nexusdev/ds-base/blob/master/src/base_test.sol#L56
